import DefaultLayout from '@/layouts/default';
import Head from 'next/head'
// import styles from '@/styles/Home.module.css'
import { ReactElement, useReducer, useState } from 'react'

const Page = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-8 py-4"></main>
    </>
  )
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <DefaultLayout headerText='Dashboard'>{page}</DefaultLayout>
  )
}

Page.pageHeadingText = "Dashboard";

export default Page;